### ISSUE TITLE
ImportError: cannot import name shell_env

### ISSUE THREAD

**Issue by cybertk** [card-io/card.io-iOS-source#33]
Cannot build with `fab build:outdir=~`, it failed with

```
ImportError: cannot import name shell_env
```

**Comment by josharian** [comment]
Is fabric in your PYTHONPATH? Does this succeed? `python -c "import fabric.context_managers"`

**Comment by cybertk** [comment]
It seems the fabric defined in `requirements.txt` is too old. `shell_env ` is introduced by Fabric 1.5.0 after a quick Google.

The issue is fixed after upgrading fabric to 1.5.0, I will provide a PR soon.
